### ISSUE TITLE
Minimization process disrupts ASPP geometry

### ISSUE THREAD

**Issue by AdriaPerezCulubret** [Acellera/acemd_issues#10]
I build the protein with PDB code 2OV5, chain A, and use HTMD built-in prepareProtein functionality. ASP 246 gets protonated and the geometry looks ok as you can see in the attached structure.pdb. 500 steps of minimization with ACEMD produces a totally disrupted geometry (output.coor) that produces simulation crash after few steps. What could be the problem? Thank you!
[equil.zip](https://github.com/Acellera/acemd_issues/files/341672/equil.zip)

**Comment by AdriaPerezCulubret** [comment]
Finally solved. The problem was that I took the crystallized waters out of the protein and then performed the prepareProtein() function and add the waters after, so the ASP 246 was protonated by the function and when appending the waters, it created a collision I did not saw.

I'll close this issue.

Thanks

**Comment by AdriaPerezCulubret** [comment]
The same problem is still there. Now, even when taking into account the water molecule when protonating, minimization still disrupts the protonated Aspartate (ASP246) geometry. The structure looks good until the equilibration process is done, where the hydrogen for the OD1/2 oxygen atom is abnormally placed, extremely close to the CG carbon.

Here's the equilibration folder. 
[equil2.zip](https://github.com/Acellera/acemd_issues/files/356819/equil2.zip)


Thank you

**Comment by mj-harvey** [comment]
@j3mdamas -- please try reproducing with the test provided.

**Comment by j3mdamas** [comment]
Will look into it on Monday.

**Comment by j3mdamas** [comment]
Closed, as it is not an acemd issue: Acellera/htmd#97
