### ISSUE TITLE
run $steps doesn't allow "1ns" notation?

### ISSUE THREAD

**Issue by GerardBCN** [Acellera/acemd_issues#21]
It run for 25000 steps and finished as completed. 1ns in theory is 250000 steps.

**Comment by mj-harvey** [comment]
With conda acemd 2016.10.27:

set steps 1ns
run $steps

correctly ran DHFR for 250,000 steps.

One thing to note is that timestep must be set before run if the number of steps is specified as a time.

**Comment by j3mdamas** [comment]
So, the 1ns notation depends on the timestep being set. I guess that this is solved if Gerard tries it. If it does not work @GerardBCN, re-open the issue.
