### ISSUE TITLE
Acemd via HTMD

### ISSUE THREAD

**Issue by shozebhaider** [Acellera/acemd_issues#22]
I am trying to use acemd that comes with htmd (via miniconda3 install). I am able to execute and run simulations via the jupyter-notebook, however that is not possible when I do it stand alone. The error message is get is that the default protocols (ff/Amber and run/NPT) that I used to invoke from the protocols folder in stand alone version have been migrated and the input file cannot find them. I tried searching for them but I could not find them.

Have the default protocols completely been done away with in this version of install ?
Is there a way to run the default protocols like in the stand alone version of Acemd?

My input file looks like this
-------------------------------start file---------------
protocol ff/Amber
protocol run/NPT

parmfile x.prmtop
bincoordinates output.coor
binvelocities output.vel
extendedsystem output.xsc
wrap on

xtcfreq 25000
energyfreq 25000
restartfreq 25000

useflexiblecell off
useconstantratio off

pluginload plug plumed
pluginarg plug input META_INP

run 215ns

**Comment by mj-harvey** [comment]
Hi Shozeb,

Apologies, the protocols are indeed missing from the current release. I'll get that fixed ASAP

**Comment by mj-harvey** [comment]
@shozebhaider You can get the protocols now by doing "conda install acemd-protocols"

Matt
