### ISSUE TITLE
acemd3

### ISSUE THREAD

**Issue by giadefa** [Acellera/acemd_issues#24]
energyoutputfreq and energyfreq ignored.

I think that matt need to have a much better compatibility check rather than us reporting things one by one.

**Comment by mj-harvey** [comment]
This is deliberate.

**Comment by mj-harvey** [comment]
energies are now output one at the beginning of the sim and then only along with the trajectory frames. That is controlled by trajectoryfreq (formerly xtcfreq)

**Comment by mj-harvey** [comment]
I haven't quite yet finished the handling of deprecated commands yet, so for now you may see unhelpful "Unknown command" messages. Eventually these will be replaced by messages explaining the replacement command name, or why a command no longer exists.
