### ISSUE TITLE
ACEMD support for non-cuboid boxes

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/acemd_issues#33]
@mj-harvey, do you think that, due to the changes of acemd, we can have support of non-cuboid boxes?

**Comment by stefdoerr** [comment]
http://docs.openmm.org/7.0.0/api-c++/generated/OpenMM.System.html

Here they mention that they support triclinic boxes

**Comment by mj-harvey** [comment]
nope

**Comment by j3mdamas** [comment]
:(
