### ISSUE TITLE
Multiple replicas metadynamics simulations on ACEMD

### ISSUE THREAD

**Issue by yiannisgaldadas** [Acellera/acemd_issues#38]
Dear ACEMD users,

Has anyone ever tried to perform a replica exchange metadynamic simulation using ACEMD?
I am trying to find a tutorial or something regarding the format of the acemd input files
but I cannot find anything even though in the manual it says that you can perform replica exchange
metadynamics with plumed2.
For instance, in Gromacs you generate a .tpr and a plumed.dat
file for each replica and using a command like to following
> mpirun -np 4 gmx_mpi mdrun -s topol -plumed plumed -multi 4

Gromacs identifies all the .tpr and plumed files in the current directory.
So I was wondering what is the equivalent "run" command to do the same in ACEMD.
I tried to have separate input file for each replica and then submit all the jobs in different GPUs
at the same time but it didn't work. 
I have ACEMD Pro license  and I am wondering how should the run command look like when you want to perform such a simulation?
Should I submit N jobs, where N is the number of replicas? Or should I use a command like
> mpirun -np 8 acemd input_replica1 input_replica2 ... input_replica_N

Best wishes,
Yiannis

**Comment by j3mdamas** [comment]
@mj-harvey, is there an input file example for replica exchange?
