### ISSUE TITLE
ACEMD - PLUMED performance

### ISSUE THREAD

**Issue by bdega** [Acellera/acemd_issues#40]
Hi,
I'm experiencing a dramatic drop in performance when using PLUMED.

More precisely, (system with about 100k atoms) unbiased MD run at almost 50 ns/day, but when calling for PLUMED2 it starts at about 20 ns/day (reasonable considering the computation added) but soon starts dropping towards 2 ns/day or less.

Please find attached input files:

[acemd_plumed.zip](https://github.com/Acellera/acemd_issues/files/1025376/acemd_plumed.zip)

Many thanks

**Comment by tonigi** [comment]
It's a common occurrence with all MD engines. Using Plumed's GRID directive may help, or at least make performance constant with n. of hills.

**Comment by j3mdamas** [comment]
@bdega could you try toni's suggestion?

**Comment by bdega** [comment]
Thank you very much for your replies.

Toni's suggestion works and now the simulation runs again at good speed! Thanks
These are the directives added, according to Plumed 2:
GRID_MIN=
GRID_MAX= 
GRID_BIN=
