### ISSUE TITLE
ACEMD_PLUGIN_DIR incorrectly set

### ISSUE THREAD

**Issue by tonigi** [Acellera/acemd_issues#41]
The `acemd` wrapper in conda sets it on the basis of `which python`, but it should be the parent directory instead. This prevents plumedXplugins.so from being found.   Suggested fix:

       DIR=$(dirname "$(which python)")/..

**Comment by j3mdamas** [comment]
Hi Toni,

From what I see, the wrapper sets `ACEMD_PLUGIN_DIR="$DIR/../lib"`. So it's already going to parent dir and then inside lib. Is this incorrect?

**Comment by tonigi** [comment]
Uhm... using package acemd 2016.10.27, and I have...

     DIR=$(dirname "$(which python)"); LD_LIBRARY_PATH="$DIR/lib/:$LD_LIBRARY_PATH"; ACEMD_PLUGIN_DIR="$DIR/lib" "$DIR/acemd.bin" $@

**Comment by j3mdamas** [comment]
You're correct, this change was made in November. It will be fixed when we release a new version

**Comment by j3mdamas** [comment]
This is already fixed on the latest version
