### ISSUE TITLE
Acemd deletes old trajectory file instead of backing up  or renaming it 

### ISSUE THREAD

**Issue by asgharrazavi** [Acellera/acemd_issues#44]
Hi,

I noticed that ACEMD will delete a trajectory file if you restart a simulation from previous restart files. For example, if you have these files: 
mol_1.xtc ,  mol_1.rs.coor, mol_1.rs.vel, mol_1.rs.xsc  
mol_2.xtc ,  mol_2.rs.coor, mol_2.rs.vel, mol_2.rs.xsc  

and you restart the simulation using mol_1.rs files, the first thing that ACEMD will do is to delete the mol_2.xtc file. Why it doesn't simply rename it say to mol_2.xtc.BAK like NAMD does, or to #mol_2.xtc.1# like GROMACS does? 

Backing up trajectory files instead of deleting them will certainly improve user experience and satisfaction.

Regards,
Asghar

**Comment by j3mdamas** [comment]
it's a feature we will consider

**Comment by giadefa** [comment]
Acemd appends on restart. This is the intended behavior.

**Comment by j3mdamas** [comment]
@giadefa I think the user means when there are no restart files. the default behaviour is to clean the previous trajectory
