### ISSUE TITLE
Cuda driver error 700 : CUDA_ERROR_ILLEGAL_ADDRESS

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/acemd_issues#45]
From https://github.com/Acellera/htmd/issues/515

```
# SWAN : FATAL : Cuda driver error 700 : CUDA_ERROR_ILLEGAL_ADDRESS : an illegal memory access was encountered
# SWAN : occured in file 'swanlibnv2.cpp' in line 2009. 
```

**Comment by j3mdamas** [comment]
Hi @federicachi

Is this general? I mean, is it happening on every machine of your Slurm cluster or only on a particular machine?

Can you tell us about the GPU specs on that machine/those machines? Running `nvidia-smi` and sending us the output should be enough.

Thank you,
João

**Comment by federicachi** [comment]
Hi @j3mdamas,
It's an Ubuntu machine and the nvidia-smi output is:
NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K20c          Off  | 0000:02:00.0     Off |                    0 |
| 30%   36C    P8    16W / 225W |      2MiB /  4742MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K20c          Off  | 0000:03:00.0     Off |                    0 |
| 30%   39C    P8    16W / 225W |      2MiB /  4742MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K20c          Off  | 0000:83:00.0     Off |                    0 |
| 30%   39C    P8    17W / 225W |      2MiB /  4742MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K20c          Off  | 0000:84:00.0     Off |                    0 |
| 30%   39C    P8    17W / 225W |      2MiB /  4742MiB |      0%      Default 


Thank you!
Federica

**Comment by j3mdamas** [comment]
Thanks. Do you have other machines where it runs?

**Comment by federicachi** [comment]
no :(

**Comment by j3mdamas** [comment]
OK, just to be sure.

**Comment by federicachi** [comment]
Sorry, but the box dimensions are in nm or in A?
I try to reduce it of a 10 factor, and the equilibration runs ...

Federica

**Comment by j3mdamas** [comment]
In angstroms. But if you're using the HTMD protocol, it should not be wrong.
