### ISSUE TITLE
removing trajectory files

### ISSUE THREAD

**Issue by alejandrovr** [Acellera/acemd_issues#5]
[1.zip](https://github.com/Acellera/acemd_issues/files/313684/1.zip)

```
[student1@ace1 input]$ tail -f e1s1_1/log.txt 
# MSHAKE: removing 1605 degrees of freedom (123942)
# There are 123942 degrees of freedom
# Setting velocity field T=300.000000K
#WARNING: cannot open file "restart.coor"
# Removing existing trajectory file output.dcd
# Removing existing trajectory file output.vel.dcd
# Removing existing trajectory file output.xtc
# Removing existing xst file output.xstfile
#     Step            Bond           Angle           Dihed            Elec             VDW              PE              KE        External          Total             Temp            Pres         PresAve
         0        780.5225       1872.8448        472.2382      -225727.0723    21156.4162      -201445.0506    36979.2171          0.0000     -164465.8335       300.2822          0.0000          0.0000
# Saved restart file at 5000
# NVML : 0 : Fan 47%     Temp 80C        Mem Used 2736MB Free 334MB Total 3071MB
# NVML : 0 : Performance state 0
      5000        707.9311       1818.8283        515.1132      -222271.5331    20251.7294      -198977.9311    36592.0539          0.0000     -162385.8772       297.1383          0.0000          0.0000
```

**Comment by giadefa** [comment]
I think that the free version shipped with htmd has a problem.

**Comment by mj-harvey** [comment]
When starting a new simulation, ACEMD now explicitly removes any pre-existing output files right at the beginning of the simulation, rather than waiting until the end of the simulation and overwriting them.
what problem exactly did this casue you?

**Comment by giadefa** [comment]
there were no trajectories files at all in the directory


On 12 July 2016 at 15:40, M J Harvey <notifications@github.com> wrote:

> When starting a new simulation, ACEMD now explicitly removes any
> pre-existing output files right at the beginning of the simulation, rather
> than waiting until the end of the simulation and overwriting them.
> what problem exactly did this casue you?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/acemd_issues/issues/5#issuecomment-232050332>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHaqOnSADlz0GVIKwfxEnyQmSEcaiOr7ks5qU5lUgaJpZM4I1JSc>
> .
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by j3mdamas** [comment]
So, from what I understand, the "Removing existing..." is outputted whether there are existing trajectory files or not. Doesn't seem like we want this behaviour to change, so I'm closing this.
