### ISSUE TITLE
Question on reading coordinates at the first frame

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/acemd_issues#6]
HI guys,

A user here needs a complicated `calcforces` setting in the system. 
Concretely the system needs:

1. harmonic restraints in some atoms (for which I use the beta column and constraints on)
2. A flatbottom potential in the ligand to prevent it explores membrane or intracellular part (which is implemented in the current input by default)
3. And TRICKY:  A flatbottom restraint two atoms to prevent they move away too much and unfold -i'm using `restrain_1D_flatbottom` for that. 

Point 3 would actually be easy by reading the beta column with `loadsystem`. But I cannot use this option as the are `constraints` are on. 
Then I just implemented the same function to just read the index using `addgroup` BUT I can't find a way to get the coordinates of the first frame for reference, as $coords($mygroup) doesn't seem to be implemented in `calcforces_init`, only in `calcforces`.

How could I read the initial coordinates? 

Fastest answer will be awarded with +100000 credits don't miss out!!!!

Noelia

**Comment by giadefa** [comment]
I seem to remember that we used to do this.
If calcforce_init does not do it, then just do it in calforces checking
that if it's the first time step

On 16 June 2016 at 22:13, Noelia Ferruz <notifications@github.com> wrote:

> HI guys,
>
> A user here needs a complicated calcforces setting in the system.
> Concretely the system needs:
>
>    1. harmonic restraints in some atoms (for which I use the beta column
>    and constraints on)
>    2. A flatbottom potential in the ligand to prevent it explores
>    membrane or intracellular part (which is implemented in the current input
>    by default)
>    3. And TRICKY: A flatbottom restraint two atoms to prevent they move
>    away too much and unfold -i'm using restrain_1D_flatbottom for that.
>
> Point 3 would actually be easy by reading the beta column with loadsystem.
> But I cannot use this option as the are constraints are on.
> Then I just implemented the same function to just read the index using
> addgroup BUT I can't find a way to get the coordinates of the first frame
> for reference, as $coords($mygroup) doesn't seem to be implemented in
> calcforces_init, only in calcforces.
>
> How could I read the initial coordinates?
>
> Fastest answer will be awarded with +100000 credits don't miss out!!!!
>
> Noelia
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/acemd_issues/issues/6>, or mute the thread
> <https://github.com/notifications/unsubscribe/AHaqOu8cqwZNT4WBKhVSrwNwlu1L0qv5ks5qMa5MgaJpZM4I3w5a>
> .
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by noeliaferruz** [comment]
True, thanks!

**Comment by mj-harvey** [comment]
if I remember correctly, You can also load an arbitrary pdb with "loadpdb"
.  AFK so can't check myself.
