### ISSUE TITLE
Error during Equilibration

### ISSUE THREAD

**Issue by KendyP** [Acellera/acemd_issues#7]
Hello,
I am trying to equilibrate a protein-membrane system and keep running into an error. The equilibration will stop before completion. The error file shows the following: Cannot fall-back to non-pairlist kernel: Type = 2. The log file shows the equilibration stopped while regenerating grid cells. When I looked at the restart file in VMD, the system was no longer in a box, but sort of a funnel shape.
This system was made the same way as previous systems, and I have not run into this error before. 
Attached is a link to a dropbox folder containing 2C.zip which has the ipython notebook used to create the system, as well as the equilibration directory with all the input files and restart files generated. Any help to fix this problem is appreciated. Thank you!
https://www.dropbox.com/sh/0zng0v0d1qy1bba/AACt21Q2_WNLpQ0k1hpkmoySa?dl=0

-Kendy

**Comment by mj-harvey** [comment]
Hi,

Almost certainly this is caused by the initial simulation cell being too
large. If there is a large pocket of vacuum in the unit cell, the baraostat
cannot remove this, and simulations tend to explode.

Matt

**Comment by KendyP** [comment]
Okay, I'll see if I can reduce the initial cell size. Thank you!

**Comment by KendyP** [comment]
I have decreased the initial size of the cell and the dimensions are now 119 x 130 x 85, which is similar to the initial size of my other systems. I am still running into the same error, unfortunately. I noticed that as equilibration runs, the restart.xsc file indicates the system keeps growing.
I have attached in a zip file the updated notebook and corresponding build/initial equilibration directories. I appreciate your help.
Thank you,
Kendy
[2C.zip](https://github.com/Acellera/acemd_issues/files/330574/2C.zip)

**Comment by giadefa** [comment]
HI,
I think that this is more a problem of building than acemd. Anyway, try this:
1) Create a new POPC120.pdb from charmmgui but this time have water solvating the polar heads. The one you are using now does not have it and equilibration is more difficult in these conditions.
2) after instead of using 
```
coo = mol.get('coords','lipids or protein')
```
use this call to guess the box size using the water of the membrane
```
coo = mol.get('coords','water') 
```

**Comment by j3mdamas** [comment]
I see some problems with your building:
* You never center the system in 0,0,0
* the point above may not actually be a problem, but the coordinates in `md.box` are taken relative to the reference center. And you are using numbers in `md.box` which are the same as of one of the tutorials and which are different from your box dimensions

**Comment by mj-harvey** [comment]
Hi, I assume @j3mdamas 's advice let you solve your problem? If not, please reopen and detail your complete model build process.
